set(ACH_QT_ROOT_DIR "" CACHE PATH "Use specific Qt folder?")
set(ACH_QT_MODULES Qt5Core Qt5Concurrent Qt5Gui Qt5Widgets Qt5LinguistTools)

include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR})
if( NOT "${ACH_QT_ROOT_DIR}" STREQUAL "")
	link_directories(${ACH_QT_ROOT_DIR}/lib)
	foreach(MODULE ${ACH_QT_MODULES})
		include(${ACH_QT_ROOT_DIR}/lib/cmake/${MODULE}/${MODULE}Config.cmake)
		include_directories(${${MODULE}_INCLUDE_DIRS})
	endforeach()
else()
	foreach(MODULE ${ACH_QT_MODULES})
		find_package(${MODULE} REQUIRED)
		include_directories(${${MODULE}_INCLUDE_DIRS})
	endforeach()
endif()